home:
  path: /
  templates: 
    - /home/kuzin57/OnlineShop/ui/html/home.html
    - /home/kuzin57/OnlineShop/ui/html/base.html
    - /home/kuzin57/OnlineShop/ui/html/footer.html

catalogue:
  path: /catalogue
  templates:
    - /home/kuzin57/OnlineShop/ui/html/catalogue.html
    - /home/kuzin57/OnlineShop/ui/html/footer.html

auth:
  path: /auth
  templates:
    - /home/kuzin57/OnlineShop/ui/html/auth.html
    - /home/kuzin57/OnlineShop/ui/html/footer.html
  auth_type: postgres

registration:
  path: /registration
  templates:
    - /home/kuzin57/OnlineShop/ui/html/register.html
  
password_recovery:
  path: /recovery
  templates:
    - /home/kuzin57/OnlineShop/ui/html/recovery.html
