version: 'v2.3.3'

services:
  bshop:
    build: ./
    command: ./web
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 7000:7000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=postgres

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 5436:5432