version: 'v2.3.3'

services:
  bshop:
    build: ./
    command: ./web
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 7000:7000
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 5436:5432